name: Bug report
description: Report a bug in Nightshift runtime, API, plugin, or docs.
title: "[bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Clear description of the issue.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact commands/actions to reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Include OS, Python, OpenCode, and install method.
      placeholder: |
        - OS:
        - Python:
        - OpenCode:
        - Nightshift:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant logs, stack traces, and command output.
      render: shell
